[package]
name = "tokio-testing"
version = "0.1.0"
authors = ["Mats Kindahl <mats.kindahl@gmail.com>"]
edition = "2018"
autoexamples = true

[dependencies]
bytes = "~0.4"
env_logger = { version = "0.5", default-features = false }
futures = "~0.1"
log = "~0.4"
tokio = "~0.1"
